<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>10</LangVersion>
    <RootNamespace>OpenDeploy.BosBridge</RootNamespace>
    <AssemblyName>opendeploy-bos-serializer</AssemblyName>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
</Project>
