/**
 * Cross-Save analysis: diff a sequence of decoded SaveForIDEV9 captures and
 * extract one canonical XML template per element / appearance type.
 *
 * Reads .scratch/captures/decoded/req-<n>/request-ap0.dec.txt for every
 * req-N dir (numeric sort), parses each ap0.__source__ DCXML, walks the
 * top-level children of <Elements> and <Appearances>, and computes the
 * "newly added" elements per save (identity not present in previous save AND
 * no `action` attribute = a fresh add, not a remove/edit).
 *
 * Output:
 *   .scratch/captures/decoded/templates/<TagName>.element.xml
 *   .scratch/captures/decoded/templates/<TagName>.appearance.xml
 *   .scratch/captures/decoded/templates/_summary.md
 *
 * Each template is the FIRST observed instance of that tag — gives the
 * canonical child-element shape we need for the RPC client to emit.
 *
 * Caveat: the parser handles balanced same-name nesting and self-closing
 * tags but doesn't validate XML strictly. Inputs are .NET XmlTextWriter
 * output so well-formedness is assumed.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

interface ElementInfo {
  tagName: string;
  raw: string;
  identity: string;
  hasAction: boolean;
  action: string | null;
}

function parseTopLevel(parentXml: string): ElementInfo[] {
  const out: ElementInfo[] = [];
  let i = 0;
  const n = parentXml.length;
  const peek = (needle: string, p: number) => parentXml.slice(p, p + needle.length) === needle;

  while (i < n) {
    while (i < n && /\s/.test(parentXml[i])) i++;
    if (i >= n) break;
    if (parentXml[i] !== '<') { i++; continue; }

    const slice = parentXml.slice(i);
    const selfClose = /^<([A-Z][A-Za-z]*)\b([^>]*)\/>/.exec(slice);
    if (selfClose) {
      const tagName = selfClose[1];
      const attrs = selfClose[2];
      const raw = selfClose[0];
      const oidM = /\boid="([^"]+)"/.exec(attrs);
      const actM = /\baction="([^"]+)"/.exec(attrs);
      out.push({
        tagName,
        raw,
        identity: oidM ? oidM[1] : '',
        hasAction: !!actM,
        action: actM ? actM[1] : null,
      });
      i += raw.length;
      continue;
    }

    const open = /^<([A-Z][A-Za-z]*)\b([^>]*)>/.exec(slice);
    if (!open) { i++; continue; }

    const tagName = open[1];
    const attrs = open[2];
    const closeTag = `</${tagName}>`;
    const openTag = `<${tagName}`;
    let depth = 1;
    let k = i + open[0].length;
    while (k < n && depth > 0) {
      if (parentXml[k] !== '<') { k++; continue; }
      if (peek(closeTag, k)) {
        depth--;
        k += closeTag.length;
        if (depth === 0) break;
        continue;
      }
      if (peek(openTag, k)) {
        const nm = /^<([A-Z][A-Za-z]*)/.exec(parentXml.slice(k));
        if (nm && nm[1] === tagName) {
          // could be open or self-close — check up to next '>'
          let j = k + nm[0].length;
          let inQ = false;
          let qc = '';
          while (j < n) {
            const c = parentXml[j];
            if (inQ) { if (c === qc) inQ = false; }
            else if (c === '"' || c === "'") { inQ = true; qc = c; }
            else if (c === '>') break;
            j++;
          }
          const isSelf = parentXml[j - 1] === '/';
          if (!isSelf) depth++;
          k = j + 1;
          continue;
        }
      }
      k++;
    }

    const raw = parentXml.slice(i, k);
    const actM = /\baction="([^"]+)"/.exec(attrs);
    const oidM = /\boid="([^"]+)"/.exec(attrs);
    // Priority: oid attr → <Key> child → <Id> child.
    // Rationale: `<Id>` is a GUID re-generated by BOS Designer every Save
    // (would falsely flag every appearance as "new" each save). `<Key>` is
    // the user-meaningful field key (e.g. F_PAIJ_Base_ffs), stable across
    // saves and unique within the form.
    let identity = oidM ? oidM[1] : '';
    if (!identity) {
      const keyM = /<Key>([^<]+)<\/Key>/.exec(raw);
      if (keyM) identity = keyM[1];
      else {
        const idM = /<Id>([^<]+)<\/Id>/.exec(raw);
        if (idM) identity = idM[1];
      }
    }
    out.push({
      tagName,
      raw,
      identity,
      hasAction: !!actM,
      action: actM ? actM[1] : null,
    });
    i = k;
  }
  return out;
}

function getSection(xml: string, tag: string): string {
  const m = new RegExp(`<${tag}>([\\s\\S]*?)</${tag}>`).exec(xml);
  return m ? m[1] : '';
}

const root = path.resolve('.scratch/captures/decoded');
if (!fs.existsSync(root)) {
  console.error(`no decoded captures at ${root} — run decode-capture.ts first`);
  process.exit(1);
}

const reqDirs = fs
  .readdirSync(root)
  .filter((d) => /^req-\d+$/.test(d))
  .map((d) => ({ id: Number(d.slice(4)), dir: d }))
  .sort((a, b) => a.id - b.id);

if (reqDirs.length === 0) {
  console.error('no req-* dirs found');
  process.exit(1);
}

const outDir = path.join(root, 'templates');
fs.mkdirSync(outDir, { recursive: true });

interface SaveInfo {
  reqId: number;
  elements: ElementInfo[];
  appearances: ElementInfo[];
  formRaw: string | null;
}

const saves: SaveInfo[] = [];
for (const { id, dir } of reqDirs) {
  const ap0Path = path.join(root, dir, 'request-ap0.dec.txt');
  if (!fs.existsSync(ap0Path)) continue;
  let ap0;
  try {
    ap0 = JSON.parse(fs.readFileSync(ap0Path, 'utf8'));
  } catch (e) {
    console.warn(`req-${id}: failed to parse ap0 — ${(e as Error).message}`);
    continue;
  }
  const xml = (ap0.__source__ ?? '') as string;
  const elementsXml = getSection(xml, 'Elements');
  const appearancesXml = getSection(xml, 'Appearances');
  const elements = parseTopLevel(elementsXml);
  const appearances = parseTopLevel(appearancesXml);
  const form = elements.find((e) => e.tagName === 'Form');
  saves.push({
    reqId: id,
    elements,
    appearances,
    formRaw: form ? form.raw : null,
  });
}

const seenElTags = new Set<string>();
const seenApTags = new Set<string>();
const summary: string[] = ['# Cross-Save Element Template Extraction', ''];
summary.push(`Sources: ${saves.length} saves (REQ ${saves.map((s) => s.reqId).join(', ')})`);
summary.push('');

let formCaptured = false;

for (let i = 0; i < saves.length; i++) {
  const cur = saves[i];
  const prev = i > 0 ? saves[i - 1] : { elements: [], appearances: [] };
  const prevElIds = new Set(prev.elements.map((e) => e.identity).filter(Boolean));
  const prevApIds = new Set(prev.appearances.map((e) => e.identity).filter(Boolean));
  const addedEl = cur.elements.filter((e) => !prevElIds.has(e.identity) && !e.hasAction);
  const addedAp = cur.appearances.filter((e) => !prevApIds.has(e.identity) && !e.hasAction);
  const removedEl = cur.elements.filter((e) => e.action === 'remove' && !prev.elements.some((p) => p.identity === e.identity && p.action === 'remove'));

  summary.push(
    i === 0
      ? `## REQ ${cur.reqId} (initial — ${cur.elements.length} el / ${cur.appearances.length} app)`
      : `## REQ ${cur.reqId}  (Δ vs REQ ${saves[i - 1].reqId})`,
  );

  if (!formCaptured && cur.formRaw) {
    const fname = path.join(outDir, '_Form.root.xml');
    fs.writeFileSync(fname, cur.formRaw);
    summary.push(`  • Form root → _Form.root.xml`);
    formCaptured = true;
  }

  for (const el of addedEl) {
    if (el.tagName === 'Form') continue;
    if (!seenElTags.has(el.tagName)) {
      seenElTags.add(el.tagName);
      fs.writeFileSync(path.join(outDir, `${el.tagName}.element.xml`), el.raw);
      summary.push(`  + element  ${el.tagName.padEnd(20)}  key=${el.identity}  → ${el.tagName}.element.xml  (${el.raw.length}B)`);
    } else {
      summary.push(`  + element  ${el.tagName.padEnd(20)}  key=${el.identity}  (already templated)`);
    }
  }
  for (const ap of addedAp) {
    if (!seenApTags.has(ap.tagName)) {
      seenApTags.add(ap.tagName);
      fs.writeFileSync(path.join(outDir, `${ap.tagName}.appearance.xml`), ap.raw);
      summary.push(`  + appearance ${ap.tagName.padEnd(28)}  key=${ap.identity}  → ${ap.tagName}.appearance.xml  (${ap.raw.length}B)`);
    } else {
      summary.push(`  + appearance ${ap.tagName.padEnd(28)}  key=${ap.identity}  (already templated)`);
    }
  }
  for (const el of removedEl) {
    summary.push(`  − remove   ${el.tagName.padEnd(20)}  oid=${el.identity}`);
  }
  if (addedEl.length === 0 && addedAp.length === 0 && removedEl.length === 0) {
    summary.push('  (no element/appearance changes — possibly no-op or property edit only)');
  }
  summary.push('');
}

summary.push('## Captured templates');
const templates = fs.readdirSync(outDir).sort();
for (const t of templates) {
  const stat = fs.statSync(path.join(outDir, t));
  summary.push(`  ${t.padEnd(40)}  ${String(stat.size).padStart(6)}B`);
}

fs.writeFileSync(path.join(outDir, '_summary.md'), summary.join('\n'));
console.log(summary.join('\n'));
console.log(`\nWrote summary: ${path.join(outDir, '_summary.md')}`);
